"""initial schema

Revision ID: 271f2a60c471
Revises: 
Create Date: 2026-08-20 09:35:56.391010

"""
from alembic import op
import sqlalchemy as sa


revision = '271f2a60c471'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bom',
    sa.Column('bom_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUPERSEDED', name='bomstatus'), nullable=True),
    sa.PrimaryKeyConstraint('bom_id')
    )
    op.create_index(op.f('ix_bom_project_id'), 'bom', ['project_id'], unique=False)
    op.create_table('bom_items',
    sa.Column('item_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('bom_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('part_id', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('po_number', sa.String(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['bom_id'], ['bom.bom_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_bom_items_part_id'), 'bom_items', ['part_id'], unique=False)
    op.create_index(op.f('ix_bom_items_po_number'), 'bom_items', ['po_number'], unique=False)
    op.create_table('coc',
    sa.Column('coc_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('bom_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bom_id'], ['bom.bom_id'], ),
    sa.PrimaryKeyConstraint('coc_id')
    )
    op.create_table('annotations',
    sa.Column('annotation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('coc_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=False),
    sa.Column('parameter', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PASS', 'FAIL', 'WARNING', name='validationstatus'), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['coc_id'], ['coc.coc_id'], ),
    sa.PrimaryKeyConstraint('annotation_id')
    )
    op.create_table('coc_entities',
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('coc_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('field_name', sa.String(), nullable=True),
    sa.Column('field_value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('extraction_method', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['coc_id'], ['coc.coc_id'], ),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_index(op.f('ix_coc_entities_field_name'), 'coc_entities', ['field_name'], unique=False)
    op.create_table('validations',
    sa.Column('validation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('coc_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('item_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('parameter', sa.String(), nullable=False),
    sa.Column('expected_value', sa.Text(), nullable=True),
    sa.Column('actual_value', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PASS', 'FAIL', 'WARNING', name='validationstatus'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['coc_id'], ['coc.coc_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['bom_items.item_id'], ),
    sa.PrimaryKeyConstraint('validation_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validations')
    op.drop_index(op.f('ix_coc_entities_field_name'), table_name='coc_entities')
    op.drop_table('coc_entities')
    op.drop_table('annotations')
    op.drop_table('coc')
    op.drop_index(op.f('ix_bom_items_po_number'), table_name='bom_items')
    op.drop_index(op.f('ix_bom_items_part_id'), table_name='bom_items')
    op.drop_table('bom_items')
    op.drop_index(op.f('ix_bom_project_id'), table_name='bom')
    op.drop_table('bom')
    # ### end Alembic commands ###
